params:
  debugMode: true
  header:
    menu:
      - name: "Home"
        tip: ":house:"
        href: ""
      - name: "Posts"
        tip: ":writing_hand:"
        href: "posts"
      - name: "About"
        tip: ":bearded_person:"
        href: "about"
  extensions:
    mathjax:
      enable: true
      res:
        js: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"
        cfg: |
          MathJax = {
            tex: { inlineMath: [['$', '$'], ['\\(', '\\)']] },
            svg: { fontCache: 'global' }
          };
    plantuml:
      enable: true
      # - Remote Server: https://plantuml.com/code-javascript-asynchronous
      # - JavaScript: https://github.com/plantuml/plantuml.js
      #   Not recommended because:
      #   - Too many files.
      #   - Slow.
      #   - High CPU usage.
      #   - TODO Not support themes.
      useRemoteServer: true
    asciinema:
      enable: true
      res:
        css: "https://cdn.jsdelivr.net/npm/asciinema-player@3/dist/bundle/asciinema-player.min.css"
        js: "https://cdn.jsdelivr.net/npm/asciinema-player@3/dist/bundle/asciinema-player.min.js"
  copyright:
    name: "Chaotic Longhair"
    email: "chaoticlonghair@gmail.com"
    since: 2023
    site: "https://gravatar.com/chaoticlonghair"
    href:
      contact: "about#contact"
      credits: "about#credits"
  license:
    badges:
      - name: "Creative Commons License"
        src: "https://licensebuttons.net/l/by-nc-sa/4.0/88x31.png"
      - name: "GNU Affero General Public License"
        src: "https://gnu.org/graphics/agplv3-88x31.png"
    href: "about#license"
